### ISSUE TITLE
I got this issue : Bitwarden-Swift-main/Swiftwarden.xcodeproj cannot be opened because it is missing its project.pbxproj file.

### ISSUE THREAD

**Issue by nguyen-tam** [jesse231/Bitwarden-Swift#1]
I got this issue : Bitwarden-Swift-main/Swiftwarden.xcodeproj cannot be opened because it is missing its project.pbxproj file. Seem you missed a file when commit code

**Comment by jesse231** [comment]
I pushed the .xcodeproj folder. Let me know if that fixed the issue.
